apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "riak.fullname" . }}
  labels:
    {{- include "riak.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "riak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "riak.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - configMap:
          defaultMode: 484
          name: riak-schemas
        name: riak-schemas
      serviceAccountName: {{ include "riak.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name:  CLUSTER_NAME
              value: "riakkv"
            - name: SERVICE_8087_NAME
              value: "riak-kv"
            - name: SERVICE_8098_NAME
              value: "riak-admin"
          volumeMounts:
          - mountPath: /etc/riak/schemas/counters.dt
            name: riak-schemas
            subPath: counters.dt
          - mountPath: /etc/riak/schemas/maps.dt
            name: riak-schemas
            subPath: maps.dt
          - mountPath: /etc/riak/schemas/sets.dt
            name: riak-schemas
            subPath: sets.dt
          ports:
            - name: http-main
              containerPort: 8087
              protocol: TCP
            - name: http-secondary
              containerPort: 8089
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
