name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - name: Configure Git
        run: |
          git config user.name "$GIT_USER"
          git config user.email "$GIT_EMAIL"
  
      - name: Add Helm repos
        run: |
          helm repo add riak https://merigo-co.github.io/helm_repository
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add consul https://helm.releases.hashicorp.com
          helm repo add treafik  https://traefik.github.io/charts
#     - name: Add repositories
 #       run: |
 #         for dir in $(ls -d charts/*/); do
 #           helm dependency list $dir 2> /dev/null | tail +2 | head -n -1 | awk '{ print "helm repo add " $1 " " $3 }' | while read cmd; do $cmd; done
 #         done

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.RELEASE_TOKEN }}"
        with:
          install_only: true
